### ISSUE TITLE
Pre-trained model please.

### ISSUE THREAD

**Issue by xiaoiker** [affromero/AUNets#2]
Hello, thanks very much for your sharing of your codes. Can you please share your pre-trained models pls. 

Actually, I have a question. As you said in the paper there are two kinds of networks: Hydra-Net and AUNets, alright? So for Hydra-Net there are 12 models, but how abouts AUNets? I means there are 36G model, are they only for Hydra-Net? if they are all two large, can you please share the  convolutional
encoder?

**Comment by affromero** [comment]
Hello, thank you for your interest. 

Yes, you are right about the two approaches. Both of them are 12 models, the main difference is that HydraNets shares the convolutional encoder. We only tested HydraNet in the simplest case scenario for RGB, and AUNets showed better performance as expected. All remaining experiments are reported using AUNets. 

Here you can find the weights for our best architecture (OF+Horizontal): http://157.253.243.8/weights/AUNets

**Comment by team2-research-easy** [comment]
Hi...the URL mentioned above is not working. can anyone update the link to download the AUNet weights?
