### ISSUE TITLE
Weights demo error

### ISSUE THREAD

**Issue by woo1** [affromero/AUNets#21]
`/AUNets/venv/lib/python3.6/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    828         if len(error_msgs) > 0:
    829             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 830                                self.__class__.__name__, "\n\t".join(error_msgs)))
    831         return _IncompatibleKeys(missing_keys, unexpected_keys)
    832 

RuntimeError: Error(s) in loading state_dict for Classifier:
        size mismatch for model.classifier.0.weight: copying a param with shape torch.Size([4096, 50176]) from checkpoint, the shape in current model is torch.Size([4096, 25088]).
`

`./main.sh -AU 04 -gpu 0 -fold 0 -OF None -DEMO Demo
`
`./main.py -- --AU=04 --fold=0 --GPU=0 --OF None --DEMO Demo --batch_size=117 --finetuning=emotionnet --mode_data=normal`

changed '--pretrained_model', '--test_model' to './fold_0/fold_0/OF_Horizontal/AU04.pth'

**Comment by affromero** [comment]
Hello, the pre-trained models provided are for `OF_Horizontal`, and the command you are providing  `./main.sh -AU 04 -gpu 0 -fold 0 -OF None -DEMO Demo` is for `-OF None`.
