### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by PatrykKotlowski** [affromero/AUNets#22]
Hello, thank you very much for sharing your code.
My question will be very basic. While training how the structure of input data should be organized? So I've got full BP4D dataset and how I can get train.txt and val.txt files. I'll be very grateful for answer.

**Comment by affromero** [comment]
Hello, thank you for your interest in our work.
It is quite simple, it must have the following form:
```
Faces/file_name0.jpg 0
Faces/file_name1.jpg 1
Faces/file_name2.jpg 1
Faces/file_name3.jpg 0
...
```
And a different folder with the pre-calculated Optical Flow
```
Faces_Flow/file_name0.jpg 0
Faces_Flow/file_name1.jpg 1
Faces_Flow/file_name2.jpg 1
Faces_Flow/file_name3.jpg 0
...
```
Please take a look at [data_loader](https://github.com/BCV-Uniandes/AUNets/blob/master/data_loader.py) script and change variables accordingly.

**Comment by PatrykKotlowski** [comment]
Thank you for answer! Now it's more clear to me.
But I've got one more qustion so in fact you're not using 2D and 3D Features from BP4D dataset?
I just need to convert AUCoding to your above format and it should work. Is that correct?

**Comment by affromero** [comment]
Yes to both of them, you are right.

**Comment by PatrykKotlowski** [comment]
Thank you again!
