### ISSUE TITLE
Bad Interpreter: No such file or directory

### ISSUE THREAD

**Issue by JRitmeester** [affromero/AUNets#25]
```
$ ./main.sh -AU 12 -gpu 0 -fold 0 -OF Horizontal -DEMO Demo
./main.py -- --AU=12 --fold=0 --GPU=0 --OF Horizontal --DEMO Demo --batch_size=24 --finetuning=emotionnet --mode_data=normal
./main.sh: ./main.py: /usr/local/bin/ipython: bad interpreter: No such file or directory
```
I'm running Python 2.7 because I'm using a pre-installed VM. Installed IPython 5.8.0 which should be compatible with Python 2.7, but the error persists. Any help is appreciated.

**Comment by affromero** [comment]
Hello, just change the first line of [main.py](https://github.com/BCV-Uniandes/AUNets/blob/master/main.py#L1) to the right interpreter, and it should work.
