### ISSUE TITLE
emotionnet trained model

### ISSUE THREAD

**Issue by huqiaoping** [affromero/AUNets#7]
Thanks for your shared pretrained models. would you please share the models trained on emotionnet  too? I find using ENet fintune can improve around10 percentage than INet in Table 1 in your paper so these models are also important.

**Comment by affromero** [comment]
Hello,
I am sorry for the late reply. We are having troubles with our server right now. In the meantime, you can find the ENet weights [in this google drive link](https://drive.google.com/open?id=1G7_abq90znBIpvBOQFf17YeUdtWMw3El). You can find more details about the training schedule in this repo: https://github.com/affromero/EmoNet.
