### ISSUE TITLE
Model Weights

### ISSUE THREAD

**Issue by Jasp012** [affromero/AUNets#8]
Hello,

I am a master student in the field of Face expression recognition at Ecole de Technologie Superieure (ETS) of Montreal. I would be interesting in obtaining model weights for AUNets. Could you provide them ? Thanks a lot for sharing. 

Best Regards,

Thomas TEIXEIRA
Master Student at Ecole de Technologie Superieure (Montreal)

**Comment by affromero** [comment]
Hello, thank you for your interest, you can find them here http://157.253.243.8/weights/AUNets/
