### ISSUE TITLE
weight model and info

### ISSUE THREAD

**Issue by segalinc** [affromero/AUNets#9]
Hello, thank you for your contribution. 
Can you please share the weights with me?

Also are these the main AU usually used for emotion recognition? I know there are other but I rarely see them in AU model prediction.

**Comment by affromero** [comment]
Hello, yes sure: http://157.253.243.8/weights/AUNets/

Those AUs are the most frequent you can find in some datasets, and I am afraid that for emotion recognition you need more than those (normally not so frequent in popular AU datasets).

**Comment by segalinc** [comment]
Thank you. I appreciate it

Cristina
